export const COMMANDE_CREATE_REQUEST = 'COMMANDE_CREATE_REQUEST';
export const COMMANDE_CREATE_SUCCESS = 'COMMANDE_CREATE_SUCCESS';
export const COMMANDE_CREATE_FAIL = 'COMMANDE_CREATE_FAIL';
export const COMMANDE_CREATE_RESET = 'COMMANDE_CREATE_RESET';

export const COMMANDE_DETAILS_FAIL = 'COMMANDE_DETAILS_FAIL';
export const COMMANDE_DETAILS_REQUEST = 'COMMANDE_DETAILS_REQUEST';
export const COMMANDE_DETAILS_SUCCESS = 'COMMANDE_DETAILS_SUCCESS';

export const COMMANDE_MINE_LIST_REQUEST = 'COMMANDE_MINE_LIST_REQUEST';
export const COMMANDE_MINE_LIST_FAIL = 'COMMANDE_MINE_LIST_FAIL';
export const COMMANDE_MINE_LIST_SUCCESS = 'COMMANDE_MINE_LIST_SUCCESS';

export const COMMANDE_LIST_REQUEST = 'COMMANDE_LIST_REQUEST';
export const COMMANDE_LIST_SUCCESS = 'COMMANDE_LIST_SUCCESS';
export const COMMANDE_LIST_FAIL = 'COMMANDE_LIST_FAIL';

export const COMMANDE_DELETE_REQUEST = 'COMMANDE_DELETE_REQUEST';
export const COMMANDE_DELETE_SUCCESS = 'COMMANDE_DELETE_SUCCESS';
export const COMMANDE_DELETE_FAIL = 'COMMANDE_DELETE_FAIL';
export const COMMANDE_DELETE_RESET = 'COMMANDE_DELETE_RESET';


export const COMMANDE_DELIVER_REQUEST = 'COMMANDE_DELIVER_REQUEST';
export const COMMANDE_DELIVER_SUCCESS = 'COMMANDE_DELIVER_SUCCESS';
export const COMMANDE_DELIVER_FAIL = 'COMMANDE_DELIVER_FAIL';
export const COMMANDE_DELIVER_RESET = 'COMMANDE_DELIVER_RESET';