export const PANIER_ADD_ITEM = 'PANIER_ADD_ITEM';
export const PANIER_REMOVE_ITEM = 'PANIER_REMOVE_ITEM';
export const PANIER_SAVE_ADRESSE_LIVRAISON = 'PANIER_SAVE_ADRESSE_LIVRAISON';
export const PANIER_SAVE_PAIEMENT = 'PANIER_SAVE_PAIEMENT';
export const PANIER_EMPTY = 'PANIER_EMPTY';


