export const PIZZA_LIST_REQUEST = 'PIZZA_LIST_REQUEST';
export const PIZZA_LIST_SUCCESS = 'PIZZA_LIST_SUCCESS';
export const PIZZA_LIST_FAIL = 'PIZZA_LIST_FAIL';


export const PIZZA_DETAILS_REQUEST = 'PIZZA_DETAILS_REQUEST';
export const PIZZA_DETAILS_SUCCESS = 'PIZZA_DETAILS_SUCCESS';
export const PIZZA_DETAILS_FAIL = 'PIZZA_DETAILS_FAIL';


export const PIZZA_CREATE_REQUEST = 'PIZZA_CREATE_REQUEST';
export const PIZZA_CREATE_SUCCESS = 'PIZZA_CREATE_SUCCESS';
export const PIZZA_CREATE_FAIL = 'PIZZA_CREATE_FAIL';
export const PIZZA_CREATE_RESET = 'PIZZA_CREATE_RESET';

export const PIZZA_UPDATE_REQUEST = 'PIZZA_UPDATE_REQUEST';
export const PIZZA_UPDATE_SUCCESS = 'PIZZA_UPDATE_SUCCESS';
export const PIZZA_UPDATE_FAIL = 'PIZZA_UPDATE_FAIL';
export const PIZZA_UPDATE_RESET = 'PIZZA_UPDATE_RESET';

export const PIZZA_DELETE_REQUEST = 'PIZZA_DELETE_REQUEST';
export const PIZZA_DELETE_SUCCESS = 'PIZZA_DELETE_SUCCESS';
export const PIZZA_DELETE_FAIL = 'PIZZA_DELETE_FAIL';
export const PIZZA_DELETE_RESET = 'PIZZA_DELETE_RESET';

export const PIZZA_AVIS_CREATE_REQUEST = 'PIZZA_AVIS_CREATE_REQUEST';
export const PIZZA_AVIS_CREATE_SUCCESS = 'PIZZA_AVIS_CREATE_SUCCESS';
export const PIZZA_AVIS_CREATE_FAIL = 'PIZZA_AVIS_CREATE_FAIL';
export const PIZZA_AVIS_CREATE_RESET = 'PIZZA_AVIS_CREATE_RESET';
